name: flutter_calendar
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl:
  hive:
  hive_flutter:
  provider:

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator:
  build_runner:
  flutter_launcher_icons:

  flutter_lints: ^2.0.0

flutter:
 uses-material-design: true

flutter_icons:
  image_path: "images/calendar-icon.webp"
  android: true
  ios: true